### ISSUE TITLE
Layout editor inventory wipe

### ISSUE THREAD

**Issue by Sonicscream** [xKaYoz/AkarianAuctionHouse#6]
When picking up items while in layout editor, it seems to delete that item once you exit the layout editor.

In addition to this, I tested it and clicked on the item that appeared whilst in the editor, and it deleted my entire inventory when I exited the editor.

**Comment by xKaYoz** [comment]
Hey there @Sonicscream!

I apologize about the problems that have occurred. When you say "clicked on the item that appeared whilst in the editor" does that mean the beforementioned item that the player picked up?

Thanks!

**Comment by xKaYoz** [comment]
Hey there @Sonicscream!

I was able to hop on real quick and replicate your issue. As for the clicking and clearing the inventory, I am not too sure on what is clearing it, but what I ended up doing was just not allowing players to pick up items while in the editor which should not bring the opportunity to click on the item to clear it. While just a temporary solution, I will try and figure out the root cause of the clearing.

Thanks again for bringing this issue to my attention!
